# Generated by Django 5.1.2 on 2024-10-25 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockhouse_data', '0002_stockprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprediction',
            name='model_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='prediction_made_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='predicted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='stockprediction',
            unique_together={('symbol', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='stockprediction',
            index=models.Index(fields=['symbol', 'timestamp'], name='blockhouse__symbol_97ecfa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprediction',
            index=models.Index(fields=['symbol', 'prediction_made_at'], name='blockhouse__symbol_e841da_idx'),
        ),
    ]
