# Generated by Django 5.1.2 on 2024-10-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockhouse_data', '0003_stockprediction_model_version_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockprediction',
            name='blockhouse__symbol_97ecfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprediction',
            name='blockhouse__symbol_e841da_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockprediction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='predicted_price',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='prediction_made_at',
        ),
    ]
